Repository kubikowski/set-utilities, pull requests merged in 2024-05, with the labels that each got.

#88 fix Jest V8 code coverage reporting
  jest.config.ts
Labels: type: Bug, code: DevOps

#89 updated dev dependencies and configuration
  .eslintrc.json
  babel.config.json
  jest.config.ts
  package-lock.json
  package.json
  test/scale/ordering/sort.function.scale.test.ts
  test/unit/ordering/sort.function.test.ts
  test/util/scale/timer.model.ts
  tsconfig.json
  tsconfig.src.json
Labels: type: Refactor, code: DevOps

#90 updated test actions
  .github/workflows/scale-test.yml
  .github/workflows/test.yml
Labels: type: Improvement, code: DevOps

#87 fix: import esm module requires extension
  src/index.ts
Labels: type: Bug, code: TypeScript

#91 updated documentation
  README.md
  package.json
Labels: type: Improvement, code: Documentation

#92 updated copyright date
  LICENSE
Labels: type: Improvement, code: Documentation
